#!/usr/bin/env bash

#############################################################################
# Danh sach cac modules duoc quyen clone. Dung cho: clone.sh, dev.sh
#############################################################################

snw_modules=(
 lightgallery
 snw-base
 snw-base-attachment
 snw-base-attachment-comp
 snw-base-auth
 snw-base-browserPush
 snw-base-browserTitle
 snw-base-comment
 snw-base-comment-comp
 snw-base-comp
 snw-base-company
 snw-base-company-comp
 snw-base-department
 snw-base-department-comp
 snw-base-dockCard
 snw-base-dockCard-comp
 snw-base-entry
 snw-base-entry-comp
 snw-base-globalUi
 snw-base-history
 snw-base-history-comp
 snw-base-jobTitle
 snw-base-jobTitle-comp
 snw-base-notification
 snw-base-notification-comp
 snw-base-notify
 snw-base-notify-comp
 snw-base-position
 snw-base-position-comp
 snw-base-profile
 snw-base-profile-comp
 snw-base-seen
 snw-base-seen-comp
 snw-base-reaction
 snw-base-reaction-comp
 snw-base-router
 snw-base-typing
 snw-base-typing-comp
 snw-base-upload
 snw-base-upload-comp
 snw-base-user
 snw-base-user-comp
 snw-base-windowState
 snw-base-permission
 snw-messenger
 snw-messenger-comp
 snw-messenger-dock
 snw-messenger-dock-comp
 snw-messenger-media
 snw-messenger-media-comp
 snw-messenger-message
 snw-messenger-message-comp
 snw-messenger-router
 snw-messenger-search
 snw-messenger-search-comp
 snw-messenger-thread
 snw-messenger-thread-comp
 snw-messenger-ui
 snw-messenger-ui-web
 snw-note
 snw-note-book
 snw-note-book-comp
 snw-note-comp
 snw-note-label
 snw-note-label-comp
 snw-note-page
 snw-note-page-comp
 snw-note-session
 snw-note-session-comp
 snw-note-subpage
 snw-note-subpage-comp
 snw-note-trash
 snw-note-trash-comp
 snw-note-ui
 snw-annc
 snw-annc-comp
 snw-annc-group
 snw-annc-group-comp
 snw-annc-pending
 snw-annc-pending-comp
 snw-annc-ui
 snw-save
 snw-save-comp
 snw-management-doc
 snw-management-doc-comp
 snw-blog
 snw-blog-comp
 snw-base-audience
 snw-base-audience-comp
 snw-base-setting
 snw-base-setting-comp
 snw-feed
 snw-feed-comp
 snw-home
 snw-home-comp
 snw-manager
 snw-manager-comp
 snw-management
 snw-management-comp
 mindmup-mapjs
 mindmup-mapjs-layout
 mindmup-mapjs-model
 emind-react
)
